NODELIST=34.64.225.90
MASTER_ADDR=
Use GPU: 0 for training
==> Making model..
The number of parameters of model is 24253410
==> Preparing data..
Files already downloaded and verified
Use GPU: 1 for training
==> Making model..
The number of parameters of model is 24253410
==> Preparing data..
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'runs/Jan26_23-43-26_34.64.225.90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/slurm-master/pytorch-multigpu/dist_parallel/train.py", line 40, in <module>
    writer = SummaryWriter()
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/writer.py", line 301, in __init__
    self._get_file_writer()
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/writer.py", line 349, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir,
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/writer.py", line 105, in __init__
    self.event_writer = EventFileWriter(
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/slurm-master/.local/lib/python3.8/site-packages/tensorboardX/record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runs/Jan26_23-43-26_34.64.225.90'
slurmstepd: error: *** STEP 73.0 ON 34.64.225.90 CANCELLED AT 2023-01-26T23:44:32 ***
slurmstepd: error: *** JOB 73 ON 34.64.225.90 CANCELLED AT 2023-01-26T23:44:32 ***
